version: '3'
services: 
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      # - <port on localhost>:<port on container> 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres 
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres 
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=87d10db4f5e00604fbea3fcd6771ce42e7c356738a0ba2aa9268338c54f83dfe
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
      
    volumes:
      - postgres-db:/var/lib/postgresql/data   # Specify the type of volume

volumes:
  postgres-db:
    # You can specify additional options for the volume if needed
