version: '3'
services: 
  api:
    image: jonisefiu/fastapi
    depends_on:
      - postgres
    ports: 
      # - <port on localhost>:<port on container> 
      - 80:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} 
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD} 
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
    volumes:
      - postgres-db:/var/lib/postgresql/data   # Specify the type of volume

volumes:
  postgres-db:
    # You can specify additional options for the volume if needed
